import org.gradle.api.logging.Logger

println "tzl love xs~~"




def x = 5
def hello() {
    x+= 5

    x
}

//hello()
//class Example {
//    static void main(String[] args) {
//        // One can see the use of a semi-colon after each statement
//        def x = 5;
//        println('Hello World');
//    }
//}

Logger logger = LoggerFactory.getLogger('some-logger')
logger.info("message from SLF4j")

